export const stories = [
  "../src/stories/accordion.stories.@(ts|tsx)",
  "../src/stories/alert.stories.@(ts|tsx)",
  "../src/stories/alert-dialog.stories.@(ts|tsx)",
  "../src/stories/autocomplete.stories.@(ts|tsx)",
  "../src/stories/avatar.stories.@(ts|tsx)",
  "../src/stories/badge.stories.@(ts|tsx)",
  "../src/stories/breadcrumbs.stories.@(ts|tsx)",
  "../src/stories/button.stories.@(ts|tsx)",
  "../src/stories/button-group.stories.@(ts|tsx)",
  "../src/stories/calendar.stories.@(ts|tsx)",
  "../src/stories/card.stories.@(ts|tsx)",
  "../src/stories/checkbox.stories.@(ts|tsx)",
  "../src/stories/checkbox-group.stories.@(ts|tsx)",
  "../src/stories/chip.stories.@(ts|tsx)",
  "../src/stories/close-button.stories.@(ts|tsx)",
  // "../src/stories/color-area.stories.@(ts|tsx)",
  // "../src/stories/color-field.stories.@(ts|tsx)",
  // "../src/stories/color-picker.stories.@(ts|tsx)",
  // "../src/stories/color-slider.stories.@(ts|tsx)",
  // "../src/stories/color-swatch.stories.@(ts|tsx)",
  // "../src/stories/color-swatch-picker.stories.@(ts|tsx)",
  "../src/stories/combo-box.stories.@(ts|tsx)",
  "../src/stories/date-field.stories.@(ts|tsx)",
  "../src/stories/date-picker.stories.@(ts|tsx)",
  "../src/stories/date-range-picker.stories.@(ts|tsx)",
  "../src/stories/disclosure.stories.@(ts|tsx)",
  "../src/stories/disclosure-group.stories.@(ts|tsx)",
  "../src/stories/drawer.stories.@(ts|tsx)",
  "../src/stories/dropdown.stories.@(ts|tsx)",
  "../src/stories/fieldset.stories.@(ts|tsx)",
  "../src/stories/input.stories.@(ts|tsx)",
  "../src/stories/input-group.stories.@(ts|tsx)",
  "../src/stories/input-otp.stories.@(ts|tsx)",
  "../src/stories/kbd.stories.@(ts|tsx)",
  "../src/stories/link.stories.@(ts|tsx)",
  "../src/stories/list-box.stories.@(ts|tsx)",
  "../src/stories/meter.stories.@(ts|tsx)",
  "../src/stories/modal.stories.@(ts|tsx)",
  "../src/stories/number-field.stories.@(ts|tsx)",
  "../src/stories/pagination.stories.@(ts|tsx)",
  "../src/stories/popover.stories.@(ts|tsx)",
  "../src/stories/progress-bar.stories.@(ts|tsx)",
  "../src/stories/progress-circle.stories.@(ts|tsx)",
  "../src/stories/radio-group.stories.@(ts|tsx)",
  "../src/stories/range-calendar.stories.@(ts|tsx)",
  "../src/stories/scroll-shadow.stories.@(ts|tsx)",
  "../src/stories/search-field.stories.@(ts|tsx)",
  "../src/stories/select.stories.@(ts|tsx)",
  "../src/stories/separator.stories.@(ts|tsx)",
  "../src/stories/skeleton.stories.@(ts|tsx)",
  "../src/stories/slider.stories.@(ts|tsx)",
  "../src/stories/spinner.stories.@(ts|tsx)",
  "../src/stories/surface.stories.@(ts|tsx)",
  "../src/stories/switch.stories.@(ts|tsx)",
  "../src/stories/switch-group.stories.@(ts|tsx)",
  // "../src/stories/table.stories.@(ts|tsx)",
  "../src/stories/tabs.stories.@(ts|tsx)",
  "../src/stories/tag-group.stories.@(ts|tsx)",
  "../src/stories/textarea.stories.@(ts|tsx)",
  "../src/stories/textfield.stories.@(ts|tsx)",
  "../src/stories/time-field.stories.@(ts|tsx)",
  "../src/stories/toast.stories.@(ts|tsx)",
  "../src/stories/toggle-button.stories.@(ts|tsx)",
  "../src/stories/toggle-button-group.stories.@(ts|tsx)",
  "../src/stories/toolbar.stories.@(ts|tsx)",
  "../src/stories/tooltip.stories.@(ts|tsx)",
  "../src/stories-extended/**/*.stories.@(ts|tsx)",
];
